# Generated by Django 3.0.5 on 2020-05-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=50)),
                ('ground', models.CharField(max_length=70)),
                ('founded_date', models.DateField()),
                ('official_website', models.URLField(max_length=70)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
    ]
