# Generated by Django 3.0.5 on 2020-05-17 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.Club'),
            preserve_default=False,
        ),
    ]
